[package]
name = "server-debugger"
version = "0.1.0"
authors = ["Guilherme G. Menaldo <guilherme.menaldo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
